### ISSUE TITLE
Issue with 9.2.1 and 9.2.2 images

### ISSUE THREAD

**Issue by p3k** [Leverex/lisertv.os#3]
I noticed that from the current three release images only 9.2.0 works for me (i.e. boots and starts Kodi as well as the configuration wizard).

The other two always end in a debugging shell:

```plain
Error in mount_storage: mount_common: Could not mount STORAGE
Starting debugging shell for boot step: mount_storage ... type exit to quit
```

I cannot really read the first line, though, because my TV is old and does not provide means to setup overscan; I assume it says something like this because I found a similar error on the [LibreElec forum](https://forum.libreelec.tv/thread/13298-oc2-8-90-005-boot-problem/?postID=99951#post99951).

(Unfortunately, the suggested manual mount does not work for me either: _Invalid argument_.)

I tried three different SD cards with 9.2.1 and 9.2.2 and got the same result. As I already was close to giving up, I tried an official Odroid Ubuntu image. This worked flawlessly, so I made a final attempt with 9.2.0 and suddenly there was LiserTV again…

Any idea what is going on?

**Comment by Leverex** [comment]
Thank you so much for reporting this issue and for your support @p3k! :1st_place_medal:

The mentioned releases are missing the device tree blob in the boot partition, which rendered them unbootable after flashing. The fix was to manually copy the ```meson8b_odroidc.dtb``` file to the boot partition. However, that's not needed anymore as I rebuilt the images and updated them in the releases section, so this issue should now be resolved. If you wish to upgrade your installation, just download the latest release again, it should work out of the box. Again, thanks for your report.

> (Unfortunately, the suggested manual mount does not work for me either: Invalid argument.)
> Any idea what is going on?

The error message seems to be related to issue #2.
My guess is that you managed to fix the boot partition by yourself, but your desktop system also modified the ```STORAGE``` partition. Remember that the 3.10 kernel can't handle some of the "new" ext4 journaling features (mounting and unmounting the partition on a modern system is enough to make it unusable with 3.10).

I found out that if I ever mounted the ```STORAGE``` ext4 partition on my desktop system, I always had to clear the journaling feature of the filesystem, to keep it compatible with the older kernel. I do that by issuing the command
```
sudo tune2fs -O ^has_journal /dev/mmcblk0p2
```
right after unmounting the ```STORAGE``` partition (the device name can be different, depending on your card reader).

**Comment by p3k** [comment]
thanks for the swift action @Leverex, gonna check out the new images asap and also try your suggestion regarding the journaling – sorry i did not connect the dots to my previous issue… i am a bit of an ignoramus regarding kernels and filesystems 😬

btw. what is the best way to upgrade the 9.2.0 installation? it does not upgrade automatically or does it? should i rather start from scratch with 9.2.2?

**Comment by Leverex** [comment]
Upgrading an existing installation can be done by manually transferring the .tar update file to ```/storage/.update```.
By using that method you won't lose any configuration (except for ```boot.ini```), because only the boot partition is affected.

Log in to your device via ssh, using username **_root_** and password **_lisertv_**, then download the .tar update via wget:
```
LiserTV:~ # wget -P /storage/.update "https://github.com/Leverex/lisertv.os/releases/download/v9.2.2/LiserTV-Odroid_C1.arm-9.2.2.tar"
```
With the next reboot the upgrade process will be shown on your screen, followed by another reboot and voilà.

**Comment by p3k** [comment]
awesome worked like a charm! thanks.

also the updated 9.2.2 image booted without any issue now.
